# Production Profile
spring:
  config:
    activate:
      on-profile: production

  datasource:
    url: ${DATABASE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  h2:
    console:
      enabled: false
      settings:
        web-allow-others: true

server:
  port: ${PORT:8080}

logging:
  level:
    com.example.contactmanagement: WARN
    org.springframework.security: WARN
    org.hibernate: WARN