# Development Profile
spring:
  config:
    activate:
      on-profile: dev

  # Database Configuration
  datasource:
    # PostgreSQL (for development)
    url: jdbc:postgresql://localhost:5432/metalbook
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres@123

  # JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update # use 'update' or 'validate' in production
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
    open-in-view: false