# Production Profile
spring:
  config:
    activate:
      on-profile: prod

  datasource:
#    url: ${URL:} postgresql://postgres:ydyhXhyqbZfgLPSUBAvkqOcYKCwzdiiz@switchyard.proxy.rlwy.net:31370/railway
    url: ${URL:jdbc:postgresql://switchyard.proxy.rlwy.net:31370/railway}
    username: postgres
    password: ydyhXhyqbZfgLPSUBAvkqOcYKCwzdiiz
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${PORT:8080}

logging:
  level:
    com.example.contactmanagement: WARN
    org.springframework.security: WARN
    org.hibernate: WARN